version: '3'

services:
  anonymousoverflow:
    container_name: anonymousoverflow
    image: codeberg.org/aryak/anonymousoverflow-docker-builds
    environment:
      - APP_URL=overflow.xn--hackerhhle-kcb.org
      - JWT_SIGNING_SECRET=secret
    networks:
      - anonymousoverflow
    ports:
      - 127.0.0.1:8090:8080
    restart: unless-stopped
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

networks:
  anonymousoverflow:
