version: '3'

services:

  caddy:
    container_name: caddy
    image: caddy:2.7-alpine
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./data:/data:rw
      - ./config:/config:rw
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE