version: "3"

services:
  quetre:
    container_name: quetre
    image: quay.io/pussthecatorg/quetre:latest
    restart: unless-stopped
    ports:
      -  "127.0.0.1:8088:3000"
    environment:
      - "NODE_ENV=production"
      - "PORT=3000"
    networks:
      - quetre
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

networks:
  quetre:
