version: "3"

services:
  libmedium:
    container_name: libmedium
    image: realaravinth/libmedium
    restart: unless-stopped
    ports:
      - 127.0.0.1:8087:7000
    volumes:
      - ./config.toml:/etc/libmedium/config.toml
    user: nobody
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    networks:
      - libmedium

networks:
  libmedium:
