version: '3'

services:
  gothub:
    container_name: gothub
    image: codeberg.org/gothub/gothub:latest
    restart: unless-stopped
    environment:
      - DOCKER=true
      - GOTHUB_SETUP_COMPLETE=true
      - GOTHUB_IP_LOGGED=false
      - GOTHUB_REQUEST_URL_LOGGED=false
      - GOTHUB_USER_AGENT_LOGGED=false
      - GOTHUB_DIAGNOSTIC_INFO_LOGGED=false
      - GOTHUB_INSTANCE_PRIVACY_POLICY=https://xn--hackerhhle-kcb.org/legal/privacy/
      - GOTHUB_INSTANCE_COUNTRY=DE
      - GOTHUB_INSTANCE_PROVIDER=Hetzner
      - GOTHUB_INSTANCE_CLOUDFLARE=false
    ports:
      - 127.0.0.1:8089:3000
    healthcheck:
      test: wget -nv --tries=1 --spider http://127.0.0.1:3000/api/v1/version || exit 1
      interval: 30s
      timeout: 5s
      retries: 2
    networks:
      - gothub
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

networks:
  gothub:
